---
abstract: 'Regexp Capture Filter For Message::Passing'
author:
  - 'chenryn <rao.chenlin@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Message-Passing-Filter-Regexp
no_index:
  directory:
    - t
    - inc
requires:
  Config::Tiny: 0
  Message::Passing: 0.11
  Regexp::Log: 0
version: 0.01
